# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2272269b96c00dbc47ab65745206d7a040eb9676f52b2fd0f9d050fa66de7f2b5756706a48e9ef0e79b588b77e86f1c5dca182d59188974da164ae583e029fe4

test:
  secret_key_base: ce7ebb82fb98677dfd7fedc053aee5e63ceb266918bd191e5d4b5027c1d06ae1b7fd1864e9aad3902483a67a01c60a885bda5bfa5dd9bf6b9d9334dd6d14ecb0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
